# 序列化 -- 读写模型 
我们现在已经讲了好多
包括 
- 如何处理数据 
- 如何构建模型
- 如何在数据上训练模型
- 如何使用不同的损失函数来做分类和回归 
但即使知道了这些，我们还是没有完全准备好来构建一个真正的机器学习模型。
下面学习如何读和写模型。 
我们需要把内存中的训练好的模型存在硬盘中下次使用 

# 读写 NDArrays
虽然我们可以使用python序列化例如Pickle,不过我们更倾向直接save或load.通常这样更快，
而且别的语言，例如R和Scala 也能用到 。 

In [1]:
from mxnet import nd 
x=nd.ones(3) 
y=nd.ones(4) 
filename='../data/test1.param'
nd.save(filename,[x,y])

读回来 

In [2]:
a,b=nd.load(filename) 
print(a,b) 


[1. 1. 1.]
<NDArray 3 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)>


不仅可以读写单个NDArray，NDArray list,dict 也是可以的：：

In [5]:
mydict={'x':x,'y':y}
filename="../data/test2.params"
nd.save(filename,mydict)

In [7]:
c=nd.load(filename)
print(c) 

{'x': 
[1. 1. 1.]
<NDArray 3 @cpu(0)>, 'y': 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)>}


# 读写Gluon模型的参数
跟NDArray 类似，Gluon 的模型（就是 nn.Block) 提供便利的save_params和load_params函数
来读写数据。我们同前一样创建一个简单的多层感知机

In [8]:
from mxnet.gluon import nn

In [9]:
def get_net():
    net=nn.Sequential()
    with net.name_scope():
        net.add(nn.Dense(10,activation='relu'))
        net.add(nn.Dense(2)) 
    return net 

net=get_net()
net.initialize() 

In [10]:
x=nd.random.uniform(shape=(2,10)) 

In [11]:
x


[[0.5488135  0.5928446  0.71518934 0.84426576 0.60276335 0.8579456
  0.5448832  0.8472517  0.4236548  0.6235637 ]
 [0.6458941  0.3843817  0.4375872  0.2975346  0.891773   0.05671298
  0.96366274 0.2726563  0.3834415  0.47766513]]
<NDArray 2x10 @cpu(0)>

In [12]:
net(x) 


[[ 0.00202203  0.00100273]
 [-0.00134863  0.00299659]]
<NDArray 2x2 @cpu(0)>

下面我们把模型参数存起来 

In [13]:
filename='../data/mlp.params'
net.save_params(filename)

/home/dske/anaconda3/envs/gluon/lib/python3.6/site-packages/mxnet/gluon/block.py:462: UserWarning: save_params is deprecated. Please use save_parameters. Note that if you want load from SymbolBlock later, please use export instead. For details, see https://mxnet.apache.org/tutorials/gluon/save_load_params.html
  warnings.warn("save_params is deprecated. Please use save_parameters. "


In [16]:
import mxnet as mx 
net2=get_net() 
net2.load_params(filename,mx.cpu()) 
print(net2(x))


[[ 0.00202203  0.00100273]
 [-0.00134863  0.00299659]]
<NDArray 2x2 @cpu(0)>
