In [1]:
import pandas 


In [2]:
titanic=pandas.read_csv('titanic_train.csv')
print(titanic.describe())

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200  


In [3]:
titanic['Age'].median()

28.0

In [4]:
titanic[:10]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [5]:
titanic['Age']=titanic['Age'].fillna(titanic['Age'].median())

In [6]:
titanic['Age'][:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5    28.0
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [7]:
titanic['Sex'].unique()

array(['male', 'female'], dtype=object)

In [8]:
titanic.loc[titanic['Sex']=='male','Sex']=0

In [9]:
titanic.loc[titanic['Sex']=='female','Sex']=1

In [10]:
titanic['Sex'].unique()

array([0, 1], dtype=object)

In [11]:
titanic['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [12]:
titanic['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [13]:
titanic['Embarked']=titanic['Embarked'].fillna('S')

In [14]:
titanic.loc[titanic['Embarked']=='S','Embarked']=0

In [15]:
titanic.loc[titanic['Embarked']=='C','Embarked']=1
titanic.loc[titanic['Embarked']=='Q','Embarked']=2

In [16]:
titanic['Embarked'].unique()

array([0, 1, 2], dtype=object)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
from sklearn.model_selection import KFold, cross_val_score

In [19]:
predictors=['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']

In [20]:
help(KFold)

Help on class KFold in module sklearn.model_selection._split:

class KFold(_BaseKFold)
 |  KFold(n_splits=5, *, shuffle=False, random_state=None)
 |  
 |  K-Folds cross-validator
 |  
 |  Provides train/test indices to split data in train/test sets. Split
 |  dataset into k consecutive folds (without shuffling by default).
 |  
 |  Each fold is then used once as a validation while the k - 1 remaining
 |  folds form the training set.
 |  
 |  Read more in the :ref:`User Guide <cross_validation>`.
 |  
 |  Parameters
 |  ----------
 |  n_splits : int, default=5
 |      Number of folds. Must be at least 2.
 |  
 |      .. versionchanged:: 0.22
 |          ``n_splits`` default value changed from 3 to 5.
 |  
 |  shuffle : bool, default=False
 |      Whether to shuffle the data before splitting into batches.
 |      Note that the samples within each split will not be shuffled.
 |  
 |  random_state : int or RandomState instance, default=None
 |      When `shuffle` is True, `random_state` af

In [72]:
alg=LinearRegression()
kf=KFold(n_splits=3,shuffle=True,random_state=1)
predictions=[]

In [73]:
for train,test in kf.split(predictors):
    train_predictors=(titanic[predictors].iloc[train,:])
    train_target=titanic['Survived'].iloc[train]
    alg.fit(train_predictors,train_target)
    test_predictions=alg.predict(titanic[predictors].iloc[test,:])
    predictions.extend(test_predictions)

In [74]:
print('1'*100)

1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111


In [75]:
predictions=[float(e) e in predictions]

SyntaxError: invalid syntax (<ipython-input-75-13dd3b064268>, line 1)

In [76]:
import numpy as np
predictions=np.array(predictions)


In [66]:
len(predictions)

7

In [77]:
predictions[predictions > .5]=1
predictions[predictions <= .5]=0

In [78]:
print(predictions)

[1. 0. 1. 1. 0. 1. 0.]


In [79]:
titanic.shape

(891, 12)

In [80]:
accuracy=sum(predictions[predictions==titanic['Survived']])/len(predictions)

/Users/lixiang/PycharmProjects/py3/py_stu/venv/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


ValueError: Lengths must match to compare