In [1]:
from mxnet import ndarray as nd

In [2]:
nd.zeros((3,4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [3]:
x=nd.ones((3,4))

In [4]:
x 


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [5]:
nd.array([[1,2],[2,3]])


[[1. 2.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>

In [6]:
y=nd.random_normal(0,1,shape=(3,4))

In [7]:
y 


[[ 2.2122064   0.7740038   1.0434403   1.1839255 ]
 [ 1.8917114  -1.2347414  -1.771029   -0.45138445]
 [ 0.57938355 -1.856082   -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

In [8]:
y.shape

(3, 4)

In [9]:
y.size 

12

In [10]:
import numpy as np


In [11]:
x=np.ones((2,3))
y=nd.array(x) 
z=y.asnumpy() 
print([z,y])

[array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32), 
[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>]


In [12]:
type(y)

mxnet.ndarray.ndarray.NDArray

In [13]:
x=nd.ones((3,4))
y=nd.ones((3,4))

before=id(y) 
y=y+x 
id(y)==before 

False

In [14]:
z=nd.zeros_like(x) 
print(z)
before=id(z) 
z[:]=x+y 
id(z)==before
print(z)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
<NDArray 3x4 @cpu(0)>


In [15]:
nd.elemwise_add(x,y,out=z) 
id(z)==before

True

自动求导 mxnet.autograd 

In [16]:
import mxnet.ndarray as nd 
import mxnet.autograd as ag

f=2*(x**2) 

In [17]:
x=nd.array([[1,2],[3,4]])

In [18]:
x 


[[1. 2.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>

In [19]:
x.attach_grad()

默认条件下，MXNet不会自动记录和构建用于求导的计算图，我们需要使用autograde 里面的record()函数来显式的要求MxNet 记录我们需要求导的程序 

In [20]:
with ag.record():
    y=x*2 
    z=y*x

接下来，我们可以通过z.backward()来进行求导，如果z不是一个标量，那么z.backward()等价于nd.sum(z).backward() 

In [21]:
z


[[ 2.  8.]
 [18. 32.]]
<NDArray 2x2 @cpu(0)>

In [22]:
z.backward()

In [23]:
x.grad==4*x


[[1. 1.]
 [1. 1.]]
<NDArray 2x2 @cpu(0)>

In [24]:
y


[[2. 4.]
 [6. 8.]]
<NDArray 2x2 @cpu(0)>

dz/dx= 4 * x 

In [25]:
def f(a):
    b=a*2 
    while nd.norm(b).asscalar()<1000:
        b=b*2
    if nd.sum(b).asscalar()>0:
        c=b
    else:
        c=100*b 
    return c

In [26]:
a=nd.random_normal(shape=3)
a.attach_grad()
with ag.record():
    c=f(a)
c.backward()

In [27]:
a.grad


[204800. 204800. 204800.]
<NDArray 3 @cpu(0)>

In [28]:
c/a 


[204800. 204800. 204800.]
<NDArray 3 @cpu(0)>

In [29]:
a 


[ 0.2444218  -0.03716067 -0.48774993]
<NDArray 3 @cpu(0)>

In [30]:
c 


[ 50057.582  -7610.505 -99891.19 ]
<NDArray 3 @cpu(0)>

In [31]:
c/a


[204800. 204800. 204800.]
<NDArray 3 @cpu(0)>