<a href="https://colab.research.google.com/github/lixixi89055465/py_stu/blob/master/tensorflow_stu/%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf 
# from tensorflow.keras import datasets,layers,optimizers 
import  tensorflow.keras as keras 


In [8]:
(x,y),(x_test,y_test)=keras.datasets.mnist.load_data() 

11493376/11490434 [==============================] - 0s 0us/step


In [9]:
x.shape

(60000, 28, 28)

In [10]:
y.shape

(60000,)

In [11]:
x.min(),x.max(),x.mean()

(0, 255, 33.318421449829934)

In [12]:
x_test.shape,y_test.shape

((10000, 28, 28), (10000,))

In [13]:
y[:4]

array([5, 0, 4, 1], dtype=uint8)

In [16]:
y_onehot=tf.one_hot(y,depth=10)

In [18]:
y_onehot[:2]

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>