# Vector Norm 

In [2]:
import tensorflow as tf 
from tensorflow.keras import datasets,layers,optimizers 


gpu_options = tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.2)
config=tf.compat.v1.ConfigProto(gpu_options=gpu_options)
session = tf.compat.v1.Session(config=config)

In [4]:
a=tf.ones([2,2])

In [6]:
tf.norm(a) # 二范数

<tf.Tensor: id=17, shape=(), dtype=float32, numpy=2.0>

In [7]:
tf.sqrt(tf.reduce_sum(tf.square(a))) 

<tf.Tensor: id=22, shape=(), dtype=float32, numpy=2.0>

In [8]:
a=tf.ones([4,28,28,3]) 
tf.norm(a)

<tf.Tensor: id=31, shape=(), dtype=float32, numpy=96.99484>

In [9]:
tf.sqrt(tf.reduce_sum(tf.square(a)))

<tf.Tensor: id=36, shape=(), dtype=float32, numpy=96.99484>

# L1 Norm 

In [11]:
b=tf.ones([2,2])

In [12]:
tf.norm(b) 

<tf.Tensor: id=45, shape=(), dtype=float32, numpy=2.0>

In [18]:
tf.norm(b,ord=2,axis=1)

<tf.Tensor: id=78, shape=(2,), dtype=float32, numpy=array([1.4142135, 1.4142135], dtype=float32)>

In [20]:
tf.norm(b,ord=1)

<tf.Tensor: id=89, shape=(), dtype=float32, numpy=4.0>

In [21]:
tf.norm(b,ord=1,axis=0)

<tf.Tensor: id=94, shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

In [22]:
tf.norm(b,ord=1,axis=1)

<tf.Tensor: id=99, shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

In [23]:
a=tf.random.normal([4,10]) 

In [24]:
tf.reduce_min(a), tf.reduce_max(a),tf.reduce_mean(a)

(<tf.Tensor: id=108, shape=(), dtype=float32, numpy=-1.7973595>,
 <tf.Tensor: id=110, shape=(), dtype=float32, numpy=1.9406475>,
 <tf.Tensor: id=112, shape=(), dtype=float32, numpy=0.018856281>)

In [25]:
tf.reduce_min(a,axis=1),tf.reduce_max(a,axis=1),tf.reduce_mean(a,axis=1)

(<tf.Tensor: id=117, shape=(4,), dtype=float32, numpy=array([-1.7973595, -1.0720425, -1.1448308, -1.4965154], dtype=float32)>,
 <tf.Tensor: id=119, shape=(4,), dtype=float32, numpy=array([1.9406475, 1.7775799, 1.3977958, 1.4094949], dtype=float32)>,
 <tf.Tensor: id=121, shape=(4,), dtype=float32, numpy=array([ 0.02185478,  0.06357749, -0.19725224,  0.18724515], dtype=float32)>)

In [26]:
tf.reduce_min(a,axis=0),tf.reduce_max(a,axis=0),tf.reduce_mean(a,axis=0)

(<tf.Tensor: id=126, shape=(10,), dtype=float32, numpy=
 array([-1.2058032 , -1.0594052 , -1.0720425 , -1.4261818 , -0.88877815,
        -0.8290164 , -0.5461778 , -0.39584246, -1.7973595 , -0.5845716 ],
       dtype=float32)>, <tf.Tensor: id=128, shape=(10,), dtype=float32, numpy=
 array([0.42500728, 0.27892086, 0.1461196 , 0.9610426 , 1.9406475 ,
        0.9614829 , 1.3977958 , 1.4094949 , 1.7775799 , 1.0917225 ],
       dtype=float32)>, <tf.Tensor: id=130, shape=(10,), dtype=float32, numpy=
 array([-0.39293805, -0.4003602 , -0.6228897 , -0.33881503,  0.6719679 ,
        -0.07697305,  0.52332985,  0.74159503, -0.29692134,  0.38056755],
       dtype=float32)>)

In [27]:
a.shape

TensorShape([4, 10])

In [28]:
tf.argmax(a).shape

TensorShape([10])

In [30]:
tf.argmax(a)

<tf.Tensor: id=137, shape=(10,), dtype=int64, numpy=array([0, 3, 0, 3, 0, 3, 2, 3, 1, 0])>

In [32]:
tf.argmax(a,axis=0)

<tf.Tensor: id=141, shape=(10,), dtype=int64, numpy=array([0, 3, 0, 3, 0, 3, 2, 3, 1, 0])>

In [33]:
tf.argmax(a,axis=1)

<tf.Tensor: id=144, shape=(4,), dtype=int64, numpy=array([4, 8, 6, 7])>

In [34]:
tf.argmin(a).shape

TensorShape([10])

In [35]:
tf.argmin(a)

<tf.Tensor: id=149, shape=(10,), dtype=int64, numpy=array([3, 0, 1, 0, 2, 1, 0, 1, 0, 1])>

# tf.equal 

In [36]:
a=tf.constant([1,2,3,2,5])

In [37]:
b=tf.range(5) 

In [38]:
tf.equal(a,b) 

<tf.Tensor: id=156, shape=(5,), dtype=bool, numpy=array([False, False, False, False, False])>

In [40]:
res=tf.equal(a,b) 

In [41]:
res

<tf.Tensor: id=158, shape=(5,), dtype=bool, numpy=array([False, False, False, False, False])>

In [42]:
tf.reduce_sum(tf.cast(res,dtype=tf.int32)) 

<tf.Tensor: id=162, shape=(), dtype=int32, numpy=0>

In [44]:
tf.cast(res,dtype=tf.int32)

<tf.Tensor: id=165, shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 0], dtype=int32)>

# Accuracy

In [46]:
a=tf.constant([[0.1,0.2,0.7],[0.9,0.05,0.05]])

In [47]:
a

<tf.Tensor: id=168, shape=(2, 3), dtype=float32, numpy=
array([[0.1 , 0.2 , 0.7 ],
       [0.9 , 0.05, 0.05]], dtype=float32)>

In [48]:
pred=tf.cast(tf.argmax(a,axis=1),dtype=tf.int32)

In [50]:
pred

<tf.Tensor: id=172, shape=(2,), dtype=int32, numpy=array([2, 0], dtype=int32)>

In [52]:
y=tf.constant([2,1])

In [54]:
tf.equal(y,pred) 

<tf.Tensor: id=177, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [57]:
correct=tf.reduce_sum(tf.cast(tf.equal(y,pred),dtype=tf.int32)) 

In [64]:
correct/y.shape[0]

<tf.Tensor: id=191, shape=(), dtype=float64, numpy=0.5>

# tf.unique

In [65]:
a=tf.range(5) 

In [66]:
tf.unique(a)

Unique(y=<tf.Tensor: id=197, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>, idx=<tf.Tensor: id=198, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>)

In [67]:
a=tf.constant([4,2,2,4,3])

In [68]:
a

<tf.Tensor: id=201, shape=(5,), dtype=int32, numpy=array([4, 2, 2, 4, 3], dtype=int32)>

In [69]:
tf.unique(a) 

Unique(y=<tf.Tensor: id=203, shape=(3,), dtype=int32, numpy=array([4, 2, 3], dtype=int32)>, idx=<tf.Tensor: id=204, shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 2], dtype=int32)>)

# Sort,argsort

In [93]:
a=tf.random.shuffle(tf.range(10,20,1)) 

In [94]:
a

<tf.Tensor: id=330, shape=(10,), dtype=int32, numpy=array([15, 14, 17, 10, 19, 18, 11, 12, 16, 13], dtype=int32)>

In [95]:
tf.sort(a,direction='DESCENDING') 

<tf.Tensor: id=340, shape=(10,), dtype=int32, numpy=array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10], dtype=int32)>

In [96]:
tf.argsort(a,direction='DESCENDING') 

<tf.Tensor: id=352, shape=(10,), dtype=int32, numpy=array([4, 5, 2, 8, 0, 1, 9, 7, 6, 3], dtype=int32)>

In [97]:
idx=tf.argsort(a,direction='DESCENDING')

In [102]:
idx,a

(<tf.Tensor: id=363, shape=(10,), dtype=int32, numpy=array([4, 5, 2, 8, 0, 1, 9, 7, 6, 3], dtype=int32)>,
 <tf.Tensor: id=330, shape=(10,), dtype=int32, numpy=array([15, 14, 17, 10, 19, 18, 11, 12, 16, 13], dtype=int32)>)

In [101]:
tf.gather(a,idx)   

<tf.Tensor: id=372, shape=(10,), dtype=int32, numpy=array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10], dtype=int32)>

In [103]:
a=tf.random.uniform([3,3],maxval=10,dtype=tf.int32) 

In [104]:
a

<tf.Tensor: id=379, shape=(3, 3), dtype=int32, numpy=
array([[0, 7, 5],
       [5, 1, 1],
       [3, 6, 3]], dtype=int32)>

In [105]:
tf.sort(a) 

<tf.Tensor: id=392, shape=(3, 3), dtype=int32, numpy=
array([[0, 5, 7],
       [1, 1, 5],
       [3, 3, 6]], dtype=int32)>

In [106]:
tf.sort(a,direction='DESCENDING') 

<tf.Tensor: id=402, shape=(3, 3), dtype=int32, numpy=
array([[7, 5, 0],
       [5, 1, 1],
       [6, 3, 3]], dtype=int32)>

In [107]:
idx=tf.argsort(a) 

In [108]:
idx

<tf.Tensor: id=415, shape=(3, 3), dtype=int32, numpy=
array([[0, 2, 1],
       [1, 2, 0],
       [0, 2, 1]], dtype=int32)>

In [110]:
 a

<tf.Tensor: id=379, shape=(3, 3), dtype=int32, numpy=
array([[0, 7, 5],
       [5, 1, 1],
       [3, 6, 3]], dtype=int32)>

In [111]:
tf.maximum(a,2)

<tf.Tensor: id=420, shape=(3, 3), dtype=int32, numpy=
array([[2, 7, 5],
       [5, 2, 2],
       [3, 6, 3]], dtype=int32)>

In [112]:
tf.minimum(a,8)

<tf.Tensor: id=423, shape=(3, 3), dtype=int32, numpy=
array([[0, 7, 5],
       [5, 1, 1],
       [3, 6, 3]], dtype=int32)>

In [114]:
a=tf.maximum(a,2)

In [115]:
a

<tf.Tensor: id=427, shape=(3, 3), dtype=int32, numpy=
array([[2, 7, 5],
       [5, 2, 2],
       [3, 6, 3]], dtype=int32)>

In [116]:
tf.minimum(a,8) 

<tf.Tensor: id=430, shape=(3, 3), dtype=int32, numpy=
array([[2, 7, 5],
       [5, 2, 2],
       [3, 6, 3]], dtype=int32)>

In [117]:
tf.clip_by_value(a,2,8)

<tf.Tensor: id=435, shape=(3, 3), dtype=int32, numpy=
array([[2, 7, 5],
       [5, 2, 2],
       [3, 6, 3]], dtype=int32)>

In [118]:
tf.clip_by_value(a,2,5)

<tf.Tensor: id=440, shape=(3, 3), dtype=int32, numpy=
array([[2, 5, 5],
       [5, 2, 2],
       [3, 5, 3]], dtype=int32)>

In [119]:
a

<tf.Tensor: id=427, shape=(3, 3), dtype=int32, numpy=
array([[2, 7, 5],
       [5, 2, 2],
       [3, 6, 3]], dtype=int32)>

In [120]:
tf.maximum(a,5)

<tf.Tensor: id=444, shape=(3, 3), dtype=int32, numpy=
array([[5, 7, 5],
       [5, 5, 5],
       [5, 6, 5]], dtype=int32)>

In [121]:
tf.minimum(a,4)

<tf.Tensor: id=447, shape=(3, 3), dtype=int32, numpy=
array([[2, 4, 4],
       [4, 2, 2],
       [3, 4, 3]], dtype=int32)>

# relu 

In [122]:
a=a-5 

In [123]:
a

<tf.Tensor: id=450, shape=(3, 3), dtype=int32, numpy=
array([[-3,  2,  0],
       [ 0, -3, -3],
       [-2,  1, -2]], dtype=int32)>

In [124]:
tf.nn.relu(a) 

<tf.Tensor: id=452, shape=(3, 3), dtype=int32, numpy=
array([[0, 2, 0],
       [0, 0, 0],
       [0, 1, 0]], dtype=int32)>

In [125]:
tf.maximum(a,0) 

<tf.Tensor: id=455, shape=(3, 3), dtype=int32, numpy=
array([[0, 2, 0],
       [0, 0, 0],
       [0, 1, 0]], dtype=int32)>

# clip_by norm 

In [127]:
a=tf.random.normal([2,2],mean=10) 

In [128]:
a

<tf.Tensor: id=462, shape=(2, 2), dtype=float32, numpy=
array([[10.118766, 11.563731],
       [11.324453, 10.117425]], dtype=float32)>

In [129]:
tf.norm(a)

<tf.Tensor: id=468, shape=(), dtype=float32, numpy=21.603584>

In [130]:
aa=tf.clip_by_norm(a,15)  # 进行归一化，并限制最大值 

In [131]:
aa

<tf.Tensor: id=486, shape=(2, 2), dtype=float32, numpy=
array([[7.0257554, 8.0290365],
       [7.8628993, 7.0248237]], dtype=float32)>