In [1]:
import tensorflow as tf 
from tensorflow.keras import datasets,layers,optimizers 


gpu_options = tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.2)
config=tf.compat.v1.ConfigProto(gpu_options=gpu_options)
session = tf.compat.v1.Session(config=config)




In [2]:
a=tf.random.normal([4,35,8])

In [3]:
tf.gather_nd(a,[[0,0],[1,1]]).shape

TensorShape([2, 8])

In [4]:
tf.gather_nd(a,[[0,0],[1,1]])

<tf.Tensor: id=10, shape=(2, 8), dtype=float32, numpy=
array([[-1.384655  ,  1.2890015 ,  1.2125483 ,  0.29029763,  0.04124366,
        -0.22851871,  1.3035239 , -1.1422329 ],
       [ 0.10995976, -1.4301234 ,  0.98775387,  0.28721023,  0.74438643,
         0.40292218, -0.8115399 , -0.4025161 ]], dtype=float32)>

In [5]:
tf.gather_nd(a,[[0,0],[1,1],[2,2]]).shape

TensorShape([3, 8])

In [7]:
tf.gather_nd(a,[[0,0],[1,1],[2,2]])

<tf.Tensor: id=17, shape=(3, 8), dtype=float32, numpy=
array([[-1.384655  ,  1.2890015 ,  1.2125483 ,  0.29029763,  0.04124366,
        -0.22851871,  1.3035239 , -1.1422329 ],
       [ 0.10995976, -1.4301234 ,  0.98775387,  0.28721023,  0.74438643,
         0.40292218, -0.8115399 , -0.4025161 ],
       [-0.5171967 , -0.7352024 , -0.348106  , -0.27375525, -0.01660214,
        -0.66439253,  1.464884  , -0.41305882]], dtype=float32)>

In [8]:
tf.gather_nd(a,[[0,0,0],[1,1,1],[2,2,2]]).shape

TensorShape([3])

In [9]:
tf.gather_nd(a,[[[0,0,0],[1,1,1],[2,2,2]]]).shape

TensorShape([1, 3])

In [12]:
tf.gather_nd(a,[[[[0,0,0],[1,1,1],[2,2,2]]]]).shape

TensorShape([1, 1, 3])

In [13]:
a=tf.random.normal([4,28,28,3])

In [15]:
tf.boolean_mask(a,mask=[True,True,False,False]).shape 

TensorShape([2, 28, 28, 3])

In [16]:
tf.boolean_mask(a,mask=[True,True,False],axis=3).shape 

TensorShape([4, 28, 28, 2])

In [17]:
a=tf.ones([2,3,4]) 

In [20]:
tf.boolean_mask(a,mask=[[True,False,False],[False,True,True]])

<tf.Tensor: id=154, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [21]:
a=tf.random.normal([4,35,8])

In [22]:
tf.gather_nd(a,[[0,0],[1,1]]).shape 

TensorShape([2, 8])

In [23]:
tf.gather_nd(a,[[0,0],[1,1],[2,2]]).shape

TensorShape([3, 8])

In [24]:
tf.gather_nd(a,[[0,0,0],[1,1,1],[2,2,2]]).shape

TensorShape([3])

In [27]:
tf.gather_nd(a,[[[0,0,0],[1,1,1],[2,2,2]]]).shape 

TensorShape([1, 3, 3])

In [28]:
a=tf.random.normal([4,28,28,3])

In [29]:
tf.boolean_mask(a,mask=[True,True,False,False]).shape 

TensorShape([2, 28, 28, 3])

In [30]:
tf.boolean_mask(a,mask=[True,True,False,False]).shape

TensorShape([2, 28, 28, 3])

In [31]:
tf.boolean_mask(a,mask=[True,True,False],axis=3).shape

TensorShape([4, 28, 28, 2])

In [32]:
a=tf.ones([2,3,4]) 

In [33]:
tf.boolean_mask(a,mask=[[True,False,False],[False,True,True]])

<tf.Tensor: id=298, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>