In [1]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras import datasets 
import os 


gpu_options = tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.2)
config=tf.compat.v1.ConfigProto(gpu_options=gpu_options)
session = tf.compat.v1.Session(config=config)

# tf.sigmoid

In [3]:
a=tf.linspace(-6.,6,10) 

In [4]:
tf.sigmoid(a)

<tf.Tensor: id=8, shape=(10,), dtype=float32, numpy=
array([0.00247264, 0.00931597, 0.03444517, 0.11920291, 0.33924365,
       0.6607564 , 0.8807971 , 0.96555483, 0.99068403, 0.9975274 ],
      dtype=float32)>

In [5]:
x=tf.random.normal([1,28,28])*5 

In [6]:
x.shape

TensorShape([1, 28, 28])

In [7]:
tf.reduce_max(x) 

<tf.Tensor: id=19, shape=(), dtype=float32, numpy=14.8078575>

In [8]:
x=tf.sigmoid(x) 

In [10]:
x.shape

TensorShape([1, 28, 28])

In [11]:
tf.reduce_min(x) ,tf.reduce_max(x)

(<tf.Tensor: id=24, shape=(), dtype=float32, numpy=1.4901161e-07>,
 <tf.Tensor: id=26, shape=(), dtype=float32, numpy=0.99999964>)

In [22]:
x=tf.random.normal([1,3,2])*5 

# tf.softmax 

In [25]:
x

<tf.Tensor: id=154, shape=(1, 3, 2), dtype=float32, numpy=
array([[[ 2.473423  ,  4.983865  ],
        [-1.3600769 ,  3.5490522 ],
        [-0.76453817,  1.1512269 ]]], dtype=float32)>

In [26]:
tf.reduce_max(x) 

<tf.Tensor: id=192, shape=(), dtype=float32, numpy=4.983865>

In [28]:
tf.nn.softmax(x,axis=1) 

<tf.Tensor: id=256, shape=(1, 3, 2), dtype=float32, numpy=
array([[[0.94261587, 0.79376894],
        [0.02039233, 0.18904401],
        [0.03699185, 0.01718702]]], dtype=float32)>

In [29]:
logits=tf.random.uniform([1,10],minval=-2,maxval=2) 

In [33]:
logits.shape

TensorShape([1, 10])

In [34]:
logits

<tf.Tensor: id=264, shape=(1, 10), dtype=float32, numpy=
array([[-0.8905301 , -0.822484  , -0.55732155, -1.5729489 , -1.1284928 ,
         1.0312581 , -0.53053904,  1.1276827 , -1.2033267 , -1.3885365 ]],
      dtype=float32)>

In [31]:
prob=tf.nn.softmax(logits,axis=1) 

In [32]:
prob

<tf.Tensor: id=265, shape=(1, 10), dtype=float32, numpy=
array([[0.04568303, 0.04889978, 0.06374785, 0.02308789, 0.03600883,
        0.31215978, 0.06547825, 0.3437586 , 0.0334125 , 0.02776345]],
      dtype=float32)>

In [35]:
tf.reduce_sum(prob,axis=1)

<tf.Tensor: id=269, shape=(1,), dtype=float32, numpy=array([0.99999994], dtype=float32)>

#  tf.tanh

In [36]:
a

<tf.Tensor: id=7, shape=(10,), dtype=float32, numpy=
array([-6.       , -4.6666665, -3.3333333, -2.       , -0.6666665,
        0.666667 ,  2.       ,  3.333334 ,  4.666667 ,  6.       ],
      dtype=float32)>

In [37]:
tf.tanh(a)

<tf.Tensor: id=272, shape=(10,), dtype=float32, numpy=
array([-0.9999877 , -0.99982315, -0.997458  , -0.9640276 , -0.58278286,
        0.5827831 ,  0.9640276 ,  0.997458  ,  0.99982315,  0.9999877 ],
      dtype=float32)>