In [2]:
import tensorflow as tf 
from tensorflow.keras import datasets,layers,optimizers 


gpu_options = tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.2)
config=tf.compat.v1.ConfigProto(gpu_options=gpu_options)
session = tf.compat.v1.Session(config=config)

+ - * / // 

In [4]:
b=tf.fill([2,2],2.)
b.shape

TensorShape([2, 2])

In [6]:
a=tf.ones([2,2])

In [7]:
a+b

<tf.Tensor: id=11, shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

In [8]:
a-b

<tf.Tensor: id=13, shape=(2, 2), dtype=float32, numpy=
array([[-1., -1.],
       [-1., -1.]], dtype=float32)>

In [9]:
a*b

<tf.Tensor: id=15, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [10]:
a/b

<tf.Tensor: id=17, shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0.5],
       [0.5, 0.5]], dtype=float32)>

In [11]:
a//b

<tf.Tensor: id=19, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [12]:
b//a

<tf.Tensor: id=21, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [13]:
b%a

<tf.Tensor: id=23, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [16]:
a

<tf.Tensor: id=10, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [17]:
tf.math.log(a)

<tf.Tensor: id=29, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [21]:
tf.math.log(b)

<tf.Tensor: id=36, shape=(2, 2), dtype=float32, numpy=
array([[0.6931472, 0.6931472],
       [0.6931472, 0.6931472]], dtype=float32)>

In [22]:
a

<tf.Tensor: id=10, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [23]:
b

<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [24]:
tf.math.log(b)

<tf.Tensor: id=40, shape=(2, 2), dtype=float32, numpy=
array([[0.6931472, 0.6931472],
       [0.6931472, 0.6931472]], dtype=float32)>

In [30]:
tf.math.log(8.)/tf.math.log(2.)

<tf.Tensor: id=55, shape=(), dtype=float32, numpy=3.0>

In [31]:
tf.math.log(100.)/tf.math.log(10.)

<tf.Tensor: id=61, shape=(), dtype=float32, numpy=2.0>

In [32]:
b

<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [33]:
tf.pow(b,3)

<tf.Tensor: id=65, shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [34]:
a,b

(<tf.Tensor: id=10, shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>)

# 矩阵相乘 

In [36]:
a@b

<tf.Tensor: id=71, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [37]:
tf.matmul(a,b)

<tf.Tensor: id=73, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [38]:
a=tf.ones([4,2,3])

In [41]:
b=tf.fill([4,3,5],2.)

In [44]:
a@b

<tf.Tensor: id=90, shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>

In [45]:
tf.matmul(a,b)

<tf.Tensor: id=92, shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>

In [46]:
a.shape

TensorShape([4, 2, 3])

In [49]:
b=tf.fill([3,5],2.0)

In [50]:
b.shape

TensorShape([3, 5])

In [53]:
a.shape

TensorShape([4, 2, 3])

In [54]:
bb=tf.broadcast_to(b,[4,3,5])

In [55]:
bb.shape

TensorShape([4, 3, 5])

In [58]:
a@bb

<tf.Tensor: id=108, shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>

In [105]:
x=tf.ones([4,2])

In [106]:
W=tf.ones([2,1]) 

In [107]:
b=tf.constant(0.1) 

In [108]:
x

<tf.Tensor: id=184, shape=(4, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [109]:
W

<tf.Tensor: id=187, shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [110]:
b

<tf.Tensor: id=188, shape=(), dtype=float32, numpy=0.1>

In [111]:
x@W+b

<tf.Tensor: id=193, shape=(4, 1), dtype=float32, numpy=
array([[2.1],
       [2.1],
       [2.1],
       [2.1]], dtype=float32)>

In [112]:
out=x@W
out

<tf.Tensor: id=195, shape=(4, 1), dtype=float32, numpy=
array([[2.],
       [2.],
       [2.],
       [2.]], dtype=float32)>

In [113]:
out=tf.nn.relu(out) 
out

<tf.Tensor: id=197, shape=(4, 1), dtype=float32, numpy=
array([[2.],
       [2.],
       [2.],
       [2.]], dtype=float32)>