<a href="https://colab.research.google.com/github/lixixi89055465/py_stu/blob/master/tensorflow_stu/%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf 
# from tensorflow.keras import datasets,layers,optimizers 
import  tensorflow.keras as keras 


In [ ]:
(x,y),(x_test,y_test)=keras.datasets.mnist.load_data() 

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
x.shape

(60000, 28, 28)

In [ ]:
y.shape

(60000,)

In [ ]:
x.min(),x.max(),x.mean()

(0, 255, 33.318421449829934)

In [ ]:
x_test.shape,y_test.shape

((10000, 28, 28), (10000,))

In [ ]:
y[:4]

array([5, 0, 4, 1], dtype=uint8)

In [ ]:
y_onehot=tf.one_hot(y,depth=10)

In [ ]:
y_onehot[:2]

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
(x,y),(x_test,y_test)=keras.datasets.cifar10.load_data() 

170500096/170498071 [==============================] - 6s 0us/step


In [ ]:
x.shape,y.shape,x_test.shape,y_test.shape

((50000, 32, 32, 3), (50000, 1), (10000, 32, 32, 3), (10000, 1))

In [ ]:
x.min(),y.min(),x.max(),y.max()

(0, 0, 255, 9)

In [ ]:
y[:4]

array([[6],
       [9],
       [9],
       [4]], dtype=uint8)

In [27]:
db=tf.data.Dataset.from_tensor_slices(x_test) 
next(iter(db)).shape

TensorShape([32, 32, 3])

In [28]:
db=tf.data.Dataset.from_tensor_slices((x_test,y_test)) 

In [29]:
next(iter(db))[0].shape

TensorShape([32, 32, 3])

In [31]:
a=next(iter(db))

In [32]:
type(a)

tuple

In [33]:
a[0].shape,a[1].shape

(TensorShape([32, 32, 3]), TensorShape([1]))

In [34]:
db=db.shuffle(10000) 

In [35]:
len(db)

10000

# .map

In [36]:
def preprocess(x,y):
  x=tf.cast(x,dtype=tf.float32)/255.0 
  y=tf.cast(y,dtype=tf.int32)
  y=tf.one_hot(y,depth=10) 
  return x,y 

In [37]:
db2=db.map(preprocess )

In [39]:
type(db)

tensorflow.python.data.ops.dataset_ops.ShuffleDataset

In [40]:
type(db2) 

tensorflow.python.data.ops.dataset_ops.MapDataset

In [41]:
res=next(iter(db2))

In [42]:
res[0].shape,res[1].shape

(TensorShape([32, 32, 3]), TensorShape([1, 10]))

In [43]:
res[1][:2]

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [48]:
next(iter(db2))[0].shape

TensorShape([32, 32, 3])

In [49]:
next(iter(db2))[1].shape

TensorShape([1, 10])

# .batch

In [50]:
db3=db2.batch(32)

In [52]:
type(db3)

tensorflow.python.data.ops.dataset_ops.BatchDataset

In [54]:
res=next(iter(db3))

In [56]:
type(res) 

tuple

In [57]:
res[0].shape

TensorShape([32, 32, 32, 3])

In [58]:
res[1].shape

TensorShape([32, 1, 10])

In [60]:
db_iter=iter(db3) 

In [71]:
def prepare_mnist_features_and_labels(x,y):
  x=tf.cast(x,tf.float32)/255.0 
  y=tf.cast(y,tf.int64) 
  return x,y 

In [72]:
def mnist_dataset():
  (x,y),(x_val,y_val)=datasets.fashion_mnist.load_data()
  y=tf.one_hot(y,depth=10) 
  y_val=tf.one_hot(y_val,depth=10) 
  
  ds=tf.data.Dataset.from_tensor_slices((x,y))
  ds=ds.map(prepare_mnist_features_and_labels) 
  ds=ds.shuffle(60000).batch(100) 
  ds_val=tf.data.Dataset.from_tensor_slices((x_val,y_val)) 
  ds_val=ds_val.map(prepare_mnist_features_and_labels) 
  ds_val=ds_val.shuffle(10000).batch(100) 
  return ds,ds_val 

In [73]:
type(db4) 

tensorflow.python.data.ops.dataset_ops.RepeatDataset