# where 

In [1]:
import tensorflow as tf 
from tensorflow.keras import datasets,layers,optimizers 
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'


In [2]:
a=tf.random.normal([3,3]) 
a.shape

TensorShape([3, 3])

In [3]:
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.9398307 ,  0.8096826 , -0.32444543],
       [-1.3681761 , -0.1901848 ,  1.0448741 ],
       [-0.34750032,  0.44391748,  0.5189814 ]], dtype=float32)>

In [4]:
mask=a>0

In [5]:
mask 

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True, False],
       [False, False,  True],
       [False,  True,  True]])>

In [6]:
tf.boolean_mask(a,mask) 

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.9398307 , 0.8096826 , 1.0448741 , 0.44391748, 0.5189814 ],
      dtype=float32)>

In [7]:
indices=tf.where(mask) 

In [8]:
indices 


<tf.Tensor: shape=(5, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 1],
       [1, 2],
       [2, 1],
       [2, 2]])>

In [9]:
tf.gather_nd(a,indices) 

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.9398307 , 0.8096826 , 1.0448741 , 0.44391748, 0.5189814 ],
      dtype=float32)>

In [10]:
mask 

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True, False],
       [False, False,  True],
       [False,  True,  True]])>

In [11]:
A=tf.ones([3,3]) 
B=tf.zeros([3,3]) 

In [12]:
tf.where(mask,A,B) 

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 0.],
       [0., 0., 1.],
       [0., 1., 1.]], dtype=float32)>

# scatter_nd

In [13]:
indices=tf.constant([[4],[3],[1],[7]]) 

In [14]:
updates=tf.constant([9,10,11,12]) 

In [15]:
shape=tf.constant([8])

In [17]:
shape

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([8], dtype=int32)>

In [16]:
tf.scatter_nd(indices,updates,shape)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 0, 11,  0, 10,  9,  0,  0, 12], dtype=int32)>