In [75]:
import pandas as pd
import matplotlib.pyplot as plt

In [76]:
columns=['mpg','cylinders','displacement','horsepower','weight','acceleration','year','origin','car name']

In [77]:
cars=pd.read_table('auto-mpg.data',delim_whitespace=True,names=columns)

In [78]:
cars.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0      130.0  3504.0          12.0    70   
1  15.0          8         350.0      165.0  3693.0          11.5    70   
2  18.0          8         318.0      150.0  3436.0          11.0    70   
3  16.0          8         304.0      150.0  3433.0          12.0    70   
4  17.0          8         302.0      140.0  3449.0          10.5    70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [79]:
cars.tail()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
393  27.0          4         140.0      86.00  2790.0          15.6    82   
394  44.0          4          97.0      52.00  2130.0          24.6    82   
395  32.0          4         135.0      84.00  2295.0          11.6    82   
396  28.0          4         120.0      79.00  2625.0          18.6    82   
397  31.0          4         119.0      82.00  2720.0          19.4    82   

     origin         car name  
393       1  ford mustang gl  
394       2        vw pickup  
395       1    dodge rampage  
396       1      ford ranger  
397       1       chevy s-10

In [80]:
dummy_cylinders=pd.get_dummies(cars['cylinders'],prefix='cyl')

In [81]:
dummy_cylinders

cyl_3  cyl_4  cyl_5  cyl_6  cyl_8
0        0      0      0      0      1
1        0      0      0      0      1
2        0      0      0      0      1
3        0      0      0      0      1
4        0      0      0      0      1
5        0      0      0      0      1
6        0      0      0      0      1
7        0      0      0      0      1
8        0      0      0      0      1
9        0      0      0      0      1
10       0      0      0      0      1
11       0      0      0      0      1
12       0      0      0      0      1
13       0      0      0      0      1
14       0      1      0      0      0
15       0      0      0      1      0
16       0      0      0      1      0
17       0      0      0      1      0
18       0      1      0      0      0
19       0      1      0      0      0
20       0      1      0      0      0
21       0      1      0      0      0
22       0      1      0      0      0
23       0      1      0      0      0
24       0      0      0      1      0
25       0      0      0      0      1
26       0      0      0      0      1
27       0      0      0      0      1
28       0      0      0      0      1
29       0      1      0      0      0
..     ...    ...    ...    ...    ...
368      0      1      0      0      0
369      0      1      0      0      0
370      0      1      0      0      0
371      0      1      0      0      0
372      0      1      0      0      0
373      0      1      0      0      0
374      0      1      0      0      0
375      0      1      0      0      0
376      0      1      0      0      0
377      0      1      0      0      0
378      0      1      0      0      0
379      0      1      0      0      0
380      0      1      0      0      0
381      0      1      0      0      0
382      0      1      0      0      0
383      0      1      0      0      0
384      0      1      0      0      0
385      0      1      0      0      0
386      0      0      0      1      0
387      0      0      0      1      0
388      0      1      0      0      0
389      0      0      0      1      0
390      0      1      0      0      0
391      0      1      0      0      0
392      0      1      0      0      0
393      0      1      0      0      0
394      0      1      0      0      0
395      0      1      0      0      0
396      0      1      0      0      0
397      0      1      0      0      0

[398 rows x 5 columns]

In [82]:
cars['cylinders']

0      8
1      8
2      8
3      8
4      8
5      8
6      8
7      8
8      8
9      8
10     8
11     8
12     8
13     8
14     4
15     6
16     6
17     6
18     4
19     4
20     4
21     4
22     4
23     4
24     6
25     8
26     8
27     8
28     8
29     4
      ..
368    4
369    4
370    4
371    4
372    4
373    4
374    4
375    4
376    4
377    4
378    4
379    4
380    4
381    4
382    4
383    4
384    4
385    4
386    6
387    6
388    4
389    6
390    4
391    4
392    4
393    4
394    4
395    4
396    4
397    4
Name: cylinders, Length: 398, dtype: int64

In [83]:
cars=pd.concat([cars,dummy_cylinders],axis=1)

In [84]:
cars.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0      130.0  3504.0          12.0    70   
1  15.0          8         350.0      165.0  3693.0          11.5    70   
2  18.0          8         318.0      150.0  3436.0          11.0    70   
3  16.0          8         304.0      150.0  3433.0          12.0    70   
4  17.0          8         302.0      140.0  3449.0          10.5    70   

   origin                   car name  cyl_3  cyl_4  cyl_5  cyl_6  cyl_8  
0       1  chevrolet chevelle malibu      0      0      0      0      1  
1       1          buick skylark 320      0      0      0      0      1  
2       1         plymouth satellite      0      0      0      0      1  
3       1              amc rebel sst      0      0      0      0      1  
4       1                ford torino      0      0      0      0      1

In [85]:
dummy_years=pd.get_dummies(cars['year'],prefix='year')

In [86]:
dummy_years.head()

year_70  year_71  year_72  year_73  year_74  year_75  year_76  year_77  \
0        1        0        0        0        0        0        0        0   
1        1        0        0        0        0        0        0        0   
2        1        0        0        0        0        0        0        0   
3        1        0        0        0        0        0        0        0   
4        1        0        0        0        0        0        0        0   

   year_78  year_79  year_80  year_81  year_82  
0        0        0        0        0        0  
1        0        0        0        0        0  
2        0        0        0        0        0  
3        0        0        0        0        0  
4        0        0        0        0        0

In [87]:
cars=pd.concat([cars,dummy_years],axis=1)

In [88]:
cars=cars.drop('year',axis=1)

In [89]:
cars.head()

mpg  cylinders  displacement horsepower  weight  acceleration  origin  \
0  18.0          8         307.0      130.0  3504.0          12.0       1   
1  15.0          8         350.0      165.0  3693.0          11.5       1   
2  18.0          8         318.0      150.0  3436.0          11.0       1   
3  16.0          8         304.0      150.0  3433.0          12.0       1   
4  17.0          8         302.0      140.0  3449.0          10.5       1   

                    car name  cyl_3  cyl_4   ...     year_73  year_74  \
0  chevrolet chevelle malibu      0      0   ...           0        0   
1          buick skylark 320      0      0   ...           0        0   
2         plymouth satellite      0      0   ...           0        0   
3              amc rebel sst      0      0   ...           0        0   
4                ford torino      0      0   ...           0        0   

   year_75  year_76  year_77  year_78  year_79  year_80  year_81  year_82  
0        0        0        0        0        0        0        0        0  
1        0        0        0        0        0        0        0        0  
2        0        0        0        0        0        0        0        0  
3        0        0        0        0        0        0        0        0  
4        0        0        0        0        0        0        0        0  

[5 rows x 26 columns]

In [90]:
cars=cars.drop('cylinders',axis=1)

In [91]:
cars.head()

mpg  displacement horsepower  weight  acceleration  origin  \
0  18.0         307.0      130.0  3504.0          12.0       1   
1  15.0         350.0      165.0  3693.0          11.5       1   
2  18.0         318.0      150.0  3436.0          11.0       1   
3  16.0         304.0      150.0  3433.0          12.0       1   
4  17.0         302.0      140.0  3449.0          10.5       1   

                    car name  cyl_3  cyl_4  cyl_5   ...     year_73  year_74  \
0  chevrolet chevelle malibu      0      0      0   ...           0        0   
1          buick skylark 320      0      0      0   ...           0        0   
2         plymouth satellite      0      0      0   ...           0        0   
3              amc rebel sst      0      0      0   ...           0        0   
4                ford torino      0      0      0   ...           0        0   

   year_75  year_76  year_77  year_78  year_79  year_80  year_81  year_82  
0        0        0        0        0        0        0        0        0  
1        0        0        0        0        0        0        0        0  
2        0        0        0        0        0        0        0        0  
3        0        0        0        0        0        0        0        0  
4        0        0        0        0        0        0        0        0  

[5 rows x 25 columns]

In [92]:
import numpy as np  

In [93]:
shuffed_rows=np.random.permutation(cars.index)

In [94]:
shuffed_cars=cars.iloc[shuffed_rows]

In [95]:
highest_train_row=int(cars.shape[0]*.70)

In [96]:
train=shuffed_cars.iloc[0:highest_train_row]

In [112]:
test=shuffed_cars.iloc[highest_train_row:]

In [113]:
from sklearn.linear_model import LogisticRegression

In [114]:
unique_origins=cars['origin'].unique()

In [115]:

unique_origins[:5]

array([1, 3, 2])

In [116]:
models={}

In [117]:
features=[c for c in train.columns if c.startswith("cyl") or c.startswith("year")]

In [118]:
features[:5]

['cyl_3', 'cyl_4', 'cyl_5', 'cyl_6', 'cyl_8']

In [119]:
for origin in unique_origins:
    model=LogisticRegression()
    X_train=train[features]
    y_train=train['origin']==origin
    model.fit(X_train,y_train)
    models[origin]=model
    

In [120]:
testing_probs=pd.DataFrame(columns=unique_origins)

In [121]:
testing_probs.head()

Empty DataFrame
Columns: [1, 3, 2]
Index: []

In [122]:
for origin in unique_origins:
    X_test=test[features]
    testing_probs[origin]=models[origin].predict_proba(X_test)[:,1]

In [123]:
predicted_origins=testing_probs.idxmax(axis=1)
print(predicted_origins)

0      3
1      3
2      1
3      1
4      1
5      1
6      1
7      3
8      1
9      1
10     3
11     1
12     2
13     1
14     1
15     3
16     1
17     1
18     1
19     1
20     1
21     3
22     3
23     1
24     1
25     3
26     3
27     1
28     1
29     2
      ..
90     1
91     1
92     3
93     1
94     1
95     1
96     1
97     1
98     1
99     1
100    1
101    3
102    1
103    1
104    1
105    1
106    1
107    1
108    1
109    1
110    1
111    2
112    1
113    2
114    1
115    2
116    1
117    1
118    1
119    1
Length: 120, dtype: int64


In [124]:
train.columns

Index(['mpg', 'displacement', 'horsepower', 'weight', 'acceleration', 'origin',
       'car name', 'cyl_3', 'cyl_4', 'cyl_5', 'cyl_6', 'cyl_8', 'year_70',
       'year_71', 'year_72', 'year_73', 'year_74', 'year_75', 'year_76',
       'year_77', 'year_78', 'year_79', 'year_80', 'year_81', 'year_82'],
      dtype='object')

In [130]:
cars['origin'].unique()

array([1, 3, 2])

In [132]:
unique_origins

array([1, 3, 2])

In [134]:
models

{1: LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
           intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
           penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
           verbose=0, warm_start=False),
 2: LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
           intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
           penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
           verbose=0, warm_start=False),
 3: LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
           intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
           penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
           verbose=0, warm_start=False)}

In [135]:
testing_probs.head()

1         3         2
0  0.234811  0.524528  0.243466
1  0.151184  0.503402  0.360071
2  0.809249  0.064765  0.127110
3  0.786376  0.147223  0.066126
4  0.776974  0.206551  0.043426

In [136]:
predicted_origins.head()

0    3
1    3
2    1
3    1
4    1
dtype: int64