In [6]:
from numpy import * 

In [9]:
a=mat('1 2 3;4 5 3')

In [10]:
a

matrix([[1, 2, 3],
        [4, 5, 3]])

In [11]:
a.I 

matrix([[-0.24561404,  0.19298246],
        [-0.0877193 ,  0.14035088],
        [ 0.47368421, -0.15789474]])

In [18]:
b=mat('-1 0 2;0 1 1;3 -1 0')

In [19]:
b.I 

matrix([[-0.14285714,  0.28571429,  0.28571429],
        [-0.42857143,  0.85714286, -0.14285714],
        [ 0.42857143,  0.14285714,  0.14285714]])

In [20]:
c=mat('-5 0 3;0 -1 6;-5 -1 9')

In [21]:
c

matrix([[-5,  0,  3],
        [ 0, -1,  6],
        [-5, -1,  9]])

In [22]:
b.I*c

matrix([[-0.71428571, -0.57142857,  3.85714286],
        [ 2.85714286, -0.71428571,  2.57142857],
        [-2.85714286, -0.28571429,  3.42857143]])

In [20]:
4/3*0.401812-1/3*0.407018

0.40007666666666664

In [22]:
4/3*0.400009-1/3*0.400002

0.40001133333333333

In [24]:
4/3*0.400009-1/3*0.400002

0.40001133333333333

In [27]:
4/3*0.426777-1/3*0.5

0.40236933333333336

In [26]:
4/3*0.407018-1/3*0.426777

0.40043166666666663