In [2]:
from mxnet import ndarray as nd

In [3]:
nd.zeros((3,4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [4]:
x=nd.ones((3,4))

In [5]:
x 


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [6]:
nd.array([[1,2],[2,3]])


[[1. 2.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>

In [7]:
y=nd.random_normal(0,1,shape=(3,4))

In [8]:
y 


[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>

In [9]:
y.shape

(3, 4)

In [10]:
y.size 

12