In [1]:
import numpy as np
a=np.random.randn(5) 

In [2]:
print(a) 

[-0.01165168  0.86723212  0.66628272 -1.13281352 -1.39456325]


In [3]:
print(a.shape) 

(5,)


In [4]:
print(a.T)

[-0.01165168  0.86723212  0.66628272 -1.13281352 -1.39456325]


In [5]:
print(np.dot(a,a.T))

4.424233118525788


In [6]:
a=np.random.randn(5,1)

In [7]:
a 

array([[-1.49108231],
       [ 0.18581156],
       [-0.80948602],
       [-0.61873554],
       [-0.48710195]])

In [8]:
print(np.dot(a,a.T))

[[ 2.22332646 -0.27706033  1.20701028  0.92258562  0.72630909]
 [-0.27706033  0.03452594 -0.15041186 -0.11496822 -0.09050917]
 [ 1.20701028 -0.15041186  0.65526761  0.50085777  0.39430221]
 [ 0.92258562 -0.11496822  0.50085777  0.38283367  0.30138729]
 [ 0.72630909 -0.09050917  0.39430221  0.30138729  0.23726831]]


In [9]:
print(np.dot(a.T,a ))

[[3.53322198]]


In [10]:
!nvidia-smi

Wed Jan 20 17:04:26 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:3B:00.0  On |                  N/A |
| 30%   45C    P2    69W / 250W |   4191MiB / 11016MiB |     14%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------