In [1]:
import numpy as np
a=np.random.randn(5) 

In [2]:
print(a) 

[ 1.089048    0.01409263 -2.5650885  -0.79582908  0.21314912]


In [3]:
print(a.shape) 

(5,)


In [4]:
print(a.T)

[ 1.089048    0.01409263 -2.5650885  -0.79582908  0.21314912]


In [5]:
print(np.dot(a,a.T))

8.444679649763332


In [6]:
a=np.random.randn(5,1)

In [7]:
a 

array([[-0.49186041],
       [ 1.24741858],
       [-0.06826686],
       [-0.92907216],
       [ 1.4773622 ]])

In [8]:
print(np.dot(a,a.T))

[[ 0.24192666 -0.61355582  0.03357777  0.45697382 -0.72665598]
 [-0.61355582  1.55605312 -0.08515735 -1.15894188  1.84288906]
 [ 0.03357777 -0.08515735  0.00466036  0.06342484 -0.10085488]
 [ 0.45697382 -1.15894188  0.06342484  0.86317509 -1.37257609]
 [-0.72665598  1.84288906 -0.10085488 -1.37257609  2.18259906]]


In [9]:
print(np.dot(a.T,a ))

[[4.84841429]]
